Squid:
  image: eksopach/squid:latest
  ports:
    - "3128:3128"
  volumes:
    - ./squid.conf:/etc/squid/squid.conf
    - ~/Volumes/squid/cache:/var/spool/squid
    - ~/Volumes/squid/log:/var/log/squid 
  restart: always
