version: "3"
services:
  squid:
    image: eksopach/squid:latest
    network_mode: "host"
    #ports:
    #  - "3128:3128"
    #  - "4128:4128"
    volumes:
      - ./squid4.conf:/etc/squid4/squid.conf
      - ~/Volumes/squid4/tls:/etc/squid4/tls
    tmpfs:
      - /var/spool/squid4
        #- ~/Volumes/squid4/cache/aufs:/var/spool/squid4/aufs
        #- ~/Volumes/squid4/cache/rock:/var/spool/squid4/rock
        #- ~/Volumes/squid4/log:/var/log/squid4
    restart: always
